apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replecas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spac:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
          - name: nginx-port
            containerPort: 80

# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
