apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: my-namespace
spec:
  limits:
  - default:
      cpu: 200m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container

# https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/

# https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/
