apiVersion: v1
kind: LimitRange
metadata:
  name: limits-min-max
  namespace: my-namespace
spec:
  limits:
  - max:
      memory: 1Gi
      cpu: 800m
    min:
      memory: 500Mi
      cpu: 200m
    type: Container

# https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace/

# https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace/
