apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-quota
  namespace: my-namespace
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"

# https://kubernetes.io/docs/concepts/policy/resource-quotas/#object-count-quota
