apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    # ingress.kubernetes.io/auth-type: basic
    # ingress.kubernetes.io/auth-secret: basic-auth
    # ingress.kubernetes.io/auth-realm: "Authentication Required - monitoring"
  name: kibana-logging
  namespace: kube-system
spec:
  rules:
    - host: kibana.io
      http:
        paths:
        - path: /
          backend:
            serviceName: kibana-logging
            servicePort: 5601
