apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - nodePort: 31001
    port: 80
    protocol: TCP
    targetPort: nginx-port
  type: NodePort

# https://kubernetes.io/docs/concepts/services-networking/service/#nodeport
