apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nginx-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        spec:
          containers:
          - name: nginx
            image: nginx:1.7.9
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: Never

# https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/

# https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/
