apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
          - name: nginx-port
            containerPort: 80
          volumeMounts:
          - name: secrets-volume
            mountPath: /etc/config
      volumes:
        - name: secrets-volume
          secret:
            secretName: nginx-secrets

# https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod
